server:
  port: 8888

spring:
  application:
    name: perfman-config-service

  cloud:
    config:
      server:
        git:
          # 有可能会遇到网络问题，导致配置服务启动失败
          uri: git@github.com:waiyuchan/perfman-config-repo.git
          search-paths: config-repo
          timeout: 30000
          clone-on-start: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
